module.exports = {
    secondary: {
        css: {
            '--tw-prose-body': 'white',
            '--tw-prose-headings': 'white',
            '--tw-prose-lead': 'white',
            '--tw-prose-links': 'rgb(var(--tertiary-400))',
            '--tw-prose-bold': 'white',
            '--tw-prose-counters': 'white',
            '--tw-prose-bullets': 'rgb(var(--secondary-200))',
            '--tw-prose-hr': 'rgb(var(--secondary-300))',
            '--tw-prose-quotes': 'white',
            '--tw-prose-quote-borders': 'rgb(var(--neutral-200))',
            '--tw-prose-captions': 'rgb(var(--neutral-200))',
            '--tw-prose-code': 'white',
            '--tw-prose-pre-code': 'white',
            '--tw-prose-pre-bg': 'rgb(var(--neutral-900))',
            '--tw-prose-th-borders': 'rgb(var(--secondary-300))',
            '--tw-prose-td-borders': 'rgb(var(--secondary-300))',
            '--tw-prose-invert-body': 'white',
            '--tw-prose-invert-headings': 'white',
            '--tw-prose-invert-lead': 'white',
            '--tw-prose-invert-links': 'rgb(var(--tertiary-400))',
            '--tw-prose-invert-bold': 'white',
            '--tw-prose-invert-counters': 'white',
            '--tw-prose-invert-bullets': 'rgb(var(--secondary-200))',
            '--tw-prose-invert-hr': 'rgb(var(--secondary-300))',
            '--tw-prose-invert-quotes': 'white',
            '--tw-prose-invert-quote-borders': 'rgb(var(--neutral-200))',
            '--tw-prose-invert-captions': 'rgb(var(--neutral-200))',
            '--tw-prose-invert-code': 'white',
            '--tw-prose-invert-pre-code': 'white',
            '--tw-prose-invert-pre-bg': 'rgb(var(--neutral-900))',
            '--tw-prose-invert-th-borders': 'rgb(var(--secondary-300))',
            '--tw-prose-invert-td-borders': 'rgb(var(--secondary-300))',
        },
    },
}
